name: Run Economap Scraper
on:
  workflow_dispatch: 
  schedule:
    - cron: '0 12 * * *'
  push:
    branches: [ main ]

jobs:
  scrape:
    runs-on: ubuntu-latest
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
      SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
      SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '24'
          cache: 'npm'
      - name: Install Dependencies
        run: npm install
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps chromium firefox
      - name: Run Scraper in Virtual Monitor
        run: xvfb-run npm run scrape
        env:
          GITHUB_ACTIONS: true
